name = "prunt"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]

executables = ["prunt"]
[[depends-on]]

[environment.SPARKLIB_OBJECT_DIR]
set = "${CRATE_ROOT}/obj/sparklib"
